### ISSUE TITLE
SRTM Freertos implementation doesn't support static api

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/mcux-sdk#10]
**Is your enhancement proposal related to a problem? Please describe.**
Only Freertos dynamic API is used. I would prefer completely static api usage.

**Describe the solution you'd like**
I will put several code changes here represent my current solution which you can consider.
*user srtm_config.h*
![image](https://user-images.githubusercontent.com/13130700/110927606-26ed1680-8326-11eb-9f33-4420bb551348.png)
*srtm_defs.h*
![image](https://user-images.githubusercontent.com/13130700/110927740-4d12b680-8326-11eb-9d0c-f15dec4cebca.png)
*srtm_mutex_freertos.c*
![image](https://user-images.githubusercontent.com/13130700/110927804-60258680-8326-11eb-9380-65f4a081e4dc.png)
*srtm_sem_freertos.c*
![image](https://user-images.githubusercontent.com/13130700/110927873-7895a100-8326-11eb-8174-c9364db57383.png)
*srtm_lfcl_service.c*
![image](https://user-images.githubusercontent.com/13130700/110927925-8e0acb00-8326-11eb-9e19-5576d15c5f3e.png)
![image](https://user-images.githubusercontent.com/13130700/110927973-9d8a1400-8326-11eb-9604-99aa424293a6.png)
*srtm_dispatcher_struct.h*
![image](https://user-images.githubusercontent.com/13130700/110928833-9adbee80-8327-11eb-9813-ffc12468079d.png)
*srtm_message_struct.h*
![image](https://user-images.githubusercontent.com/13130700/110928900-ac24fb00-8327-11eb-9655-a9e8207d80e1.png)
*srtm_peercore_struct*
![image](https://user-images.githubusercontent.com/13130700/110928962-bc3cda80-8327-11eb-8262-b789cf52ce75.png)
*srtm_peercore.c*
![image](https://user-images.githubusercontent.com/13130700/110929045-d1b20480-8327-11eb-8f9a-4a57e902365e.png)
*srtm_mutex.h*
![image](https://user-images.githubusercontent.com/13130700/110929109-e7272e80-8327-11eb-864e-5a0972efa2bf.png)
*srtm_sem.h*
![image](https://user-images.githubusercontent.com/13130700/110929178-fc03c200-8327-11eb-96cc-6b4c60c7d608.png)
*srtm_dispatcher.c*
![image](https://user-images.githubusercontent.com/13130700/110929248-0e7dfb80-8328-11eb-977e-8911e9cf8646.png)
![image](https://user-images.githubusercontent.com/13130700/110929272-13db4600-8328-11eb-8a60-2f3de7ce816c.png)
![image](https://user-images.githubusercontent.com/13130700/110929296-1ccc1780-8328-11eb-96ab-1ec76219acf2.png)

**Describe alternatives you've considered**
-

**Additional context**
Similar to #7, #8, #9

Things need to be solved which are not yet covered: SRTM_Heap_Malloc and SRTM_Heap_Free

**Comment by mcuxsusan** [comment]
Hi @Hadatko, would you like to directly improve our code by direct pull request? I have added more components on latest main branch, and the srtm component is now included.

**Comment by Hadatko** [comment]
Sure. Thank you. Will do tomorrow.

**Comment by Hadatko** [comment]
I am closing this issue as PR was created.

**Comment by Hadatko** [comment]
Hi @mcuxsusan , i am reopening this issue as i noticed that not all requests were matched (i missed that last time, but i am doing update now and i see missing one file changes).
It looks like srtm_lfcl_service.c changes were not applied.
*srtm_lfcl_service.c*
![image](https://user-images.githubusercontent.com/13130700/110927925-8e0acb00-8326-11eb-9e19-5576d15c5f3e.png)
![image](https://user-images.githubusercontent.com/13130700/110927973-9d8a1400-8326-11eb-9604-99aa424293a6.png)

But to match srtm static dynamic definition it should looks like:
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/13130700/9ad94214-0b17-4007-8c02-fa85e1ccf86a)
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/13130700/f072c395-041a-48c9-b5f7-2a03cc1b4a91)

**Comment by mcuxsusan** [comment]
Hi @Hadatko, thanks for your active communication! I saw you have opened the pr, will inform the dev team to help review it. Hope we could get the pr merged soon.

**Comment by Hadatko** [comment]
Hi @mcuxsusan thank you very much. Just note that the comment in this issue cannot be done by PR as file is not present in repository officialy. The PR you are mentioning is related to other srtm files which are present in this repository.

**Comment by MichalPrincNXP** [comment]
Thank you Dusan, I do not know why this srtm_lfcl_service.c is not part of github release, but anyway, internal update requested and the fix will be provided in the next release. Can we close this ticket now?

**Comment by MichalPrincNXP** [comment]
OK, let's wait once the internal PR is approved and merged internally and I will close the issue then.

**Comment by Hadatko** [comment]
Sounds great 🤞

**Comment by MichalPrincNXP** [comment]
Internal PR is approved and the fix is merged to be ready in the next MCUXpresso SDK 2.16.000 release
