### ISSUE TITLE
SPDIF DMA fsl driver does not work on rt1176 M4 core

### ISSUE THREAD

**Issue by svoulaz** [nxp-mcuxpresso/mcux-sdk#115]
Hello,
in SDK 2.13.1 for rt1176 EVK, the SPDIF DMA driver is missing address-remapping on TCDs for DMA access to cm4 TCM. Specifically, in the function SPDIF_SubmitTransfer() (fsl_spdif_edma.c), TCD address for DLAST_SGA (assignment and subsequest checks) is not translated.

The SDK sample evkmimxrt1170_spdif_edma_transfer_cm4 does not work (the equivalent version for cm7 core does). For SPDIF driver to work on cm4 core, the code in SPDIF_SubmitTransfer() body should match EDMA_SubmitTransfer(), including MEMORY_ConvertMemoryMapAddress() calls where/when needed.

**Comment by mcuxsusan** [comment]
Thanks for reporting the issue! Already forwarded the issue to develop team, feedback may be delayed.
