### ISSUE TITLE
Update develoipment GCC ARM toolchain to an up-to-date one

### ISSUE THREAD

**Issue by escherstair** [nxp-mcuxpresso/mcux-sdk#123]
Even the [latest 2.13.1 release](https://github.com/nxp-mcuxpresso/mcux-sdk/releases/tag/MCUX_2.13.1) of mcux-sdk refers to an old GCC toolchain
![immagine](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/22594460/68cb354f-d313-4573-8e61-9c7dd3d33395)

10.3-2021.10 is the latest one listed on the old (deprecated) pages:

- [https://launchpad.net/gcc-arm-embedded](https://launchpad.net/gcc-arm-embedded)
  
![immagine](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/22594460/4461ed0a-b8a4-4ff4-a173-8d7d0a9215d9)

- [https://developer.arm.com/downloads/-/gnu-rm](https://developer.arm.com/downloads/-/gnu-rm)
  
![immagine](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/22594460/21b32236-ddae-4db1-9baf-4199e64b8e57)

The latest up-to-date toolchains are available on [https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads)

I ask NXP to update the GCC ARM toolchain to an up-to-date one.
Thanks

**Comment by mcuxsusan** [comment]
Hi @escherstair, thanks for raising this topic. However, we are not able to always use the up-to-date version of toolchain, it depends. If the toolchain latest release matches our software release schedule, then our software release uses the latest version of toolchain, else not.

For your information, for the coming 2.14.0 release(planned in early August) we will use the GCC 12.2.1 which is the latest version.
