### ISSUE TITLE
There is no manifest for FRDM-K64F and therefore there is no way to import FRDM-K64F examples.

### ISSUE THREAD

**Issue by iustmehri** [nxp-mcuxpresso/mcux-sdk#136]

**Comment by mcuxsusan** [comment]
Hi @iustmehri, could you please help provide more details? Which IDE are you using to explore our sdk? The MCUXpresso IDE or our mcuxpresso vscode extension? I assumed that you have followed the suggestion to use west tool to get our full delivery of SDK. In the west way of getting full sdk, the manifest file for FRDM-K64F could be found in the **examples/manifests** path. If you are using MCUXpresso IDE, could you please select manifest path to examples/manifest when importing sdk as git repository? See below pic as a reference:
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/80874628/b25836b0-8ee9-4f2f-aa4c-4493a3544a3d)

**Comment by iustmehri** [comment]
Hello @mcuxsusan! Thanks for the answere. I use the mcuxpresso vscode extension and to get the SDK I use the interface provided by the extension.

**Comment by iustmehri** [comment]
Thank you so much @mcuxsusan

**Comment by xtrollyj00** [comment]
Still experiencing the same problem, I am using extension for VSCode.

**Comment by mcuxsusan** [comment]
Hi @xtrollyj00, checking with the team on the release plan of VSCode extension update which integrates the manifests selection. I will share with you the plan once I get the information.

**Comment by mcuxsusan** [comment]
Checked with the team, the next release with the update integrated targets the end of October.

Thanks,
Susan

From: xtrollyj00 ***@***.***>
Sent: 2023年10月18日 4:34
To: nxp-mcuxpresso/mcux-sdk ***@***.***>
Cc: Susan Su ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [nxp-mcuxpresso/mcux-sdk] There is no manifest for FRDM-K64F and therefore there is no way to import FRDM-K64F examples. (Issue #136)

Caution: This is an external email. Please take care when clicking links or opening attachments. When in doubt, report the message using the 'Report this email' button


Still experiencing the same problem, I am using extension for VSCode.

―

**Comment by xtrollyj00** [comment]
Thank you @mcuxsusan.

**Comment by mcuxsusan** [comment]
I checked the latest vscode extension(v1.3.59) and find the FRDM-K64F board is now displayed, see as below:
![image](https://github.com/nxp-mcuxpresso/mcux-sdk/assets/80874628/37ade1c6-bf08-47ff-aaa0-ec691c9d8a2f)
