### ISSUE TITLE
missing version (2.15)

### ISSUE THREAD

**Issue by jsiverskog** [nxp-mcuxpresso/mcux-sdk#161]
hi,
mcux version 2.15 was released a couple of days ago, but i can't see any tag for it here.

the entire sdk handling is a bit confusing to me - there's the nxp sdk builder, there's this git repository, and there's a way to directly download sdk:s in mcuxpresso ide.

what is the 'correct' way? i would prefer to use git and west.

**Comment by mcuxsusan** [comment]
Also for your question, which way is suggested to get our latest SDK update, it belongs to your preference. 

As you already listed, yes, we have user configurable SDK packages distribution in nxp SDK builder and MCUXpresso IDE, but in that way user may only build SDK package for one platform/soc each time. In this Github repo, we usually do release update for a list of platform/devices. For example, in the MCUX_2.14.0 release, we release all platform/socs which have 2.14.0 RFP quality, see https://github.com/nxp-mcuxpresso/mcux-sdk/releases/tag/MCUX_2.14.0.

If you are familiar with Git, working on multiple parts/socs of NXP and do not care that much about the speed of size, OK with only armgcc/MCUX toolchain for examples, using this repo will be highly recommended. Using the repo way will easily get fix.

Using SDK package is preferred if you are:
- focused working on one platform/soc
- Care of the speed of getting SDK and size of SDK
- Want full middleware support in SDK
- Want full toolchain support for SDK examples including IAR/MDK/ARMGCC/MCUXIDE

**Comment by mcuxsusan** [comment]
2.15.000 release now public in https://github.com/nxp-mcuxpresso/mcux-sdk/releases/tag/MCUX_2.15.000.

**Comment by jsiverskog** [comment]
hi,
same now for v2.16.000 @mcuxsusan
