### ISSUE TITLE
Boot from flash

### ISSUE THREAD

**Issue by Jandro20** [nxp-mcuxpresso/mcux-sdk#177]
**Describe the bug**
Hello

I'm currently working with [TQMa117xL](https://www.tq-group.com/en/products/tq-embedded/arm-architecture/tqma117xl/) and use this [bsp](https://github.com/tq-systems/MBa117xL.SW.MCU.BSP) Already, we have a demo application with the default configuration explained in [README.md](https://github.com/tq-systems/MBa117xL.SW.MCU.BSP/blob/main/README.md). We can generate the binary with debug+ram and debug with [Ozone debugger - Segger](https://www.segger.com/products/development-tools/ozone-j-link-debugger/). The next step is to flash the device and boot from flash 

**To Reproduce**

- Environment (please complete the following information):
  - Tag/Commit hash: MCUX_2.14.0
  - Toolchain: arm-gnu-toolchain-12.2.rel1-arm-none-eabi
  - Board/SoC: TQMa117xL module
  - Example demo_hello_world
- Steps to reproduce the behavior:
    To flash the device, we recompile with debug+flash configuration and use [MCUXpresso Secure Provisioning Tool](https://www.nxp.com/design/design-center/software/development-software/mcuxpresso-software-and-tools-/mcuxpresso-secure-provisioning-tool:MCUXPRESSO-SECURE-PROVISIONING) with the necessary configuration to flash into TQMa117xL, we follow the normal process to upload the binary into flash, with burned fuses and boot mode needed. (This process is already tested with other binary generated with [MCUXpresso Integrated Development Environment (IDE)](https://www.nxp.com/design/design-center/software/development-software/mcuxpresso-software-and-tools-/mcuxpresso-integrated-development-environment-ide:MCUXpresso-IDE))

**Expected behavior**

The normal process in Secure Provisioning return a SUCCESS result, but when we reboot the board with Internal Boot mode, the binary is not loaded and the board have not code loaded.

Is it needed an additional process to flash the board?

Please let me know if you need additional information.

Thanks!

**Comment by mcuxsusan** [comment]
Hi @Jandro20, this BSP/board seems not be released by official NXP, thus our development team does not have the environment to support the issue, it will be closed.
