### ISSUE TITLE
Using I2S in RX and TX mode at the same time

### ISSUE THREAD

**Issue by carlocaione** [nxp-mcuxpresso/mcux-sdk#195]
I'm trying to understand whether this is an API or hardware limitation.

I want to use the I2S controller in TX and RX mode **at the same time** but all the APIs seems to suggest that you can configure the controller either for TX or for RX (see for example `I2S_RxInit()` vs `I2S_TxInit()`).

Is this simply an API limitation or is there anything in hardware preventing that?

**Comment by mcuxsusan** [comment]
Wait for development team to check. Appreciate your patience since reply could be delayed.

**Comment by carlocaione** [comment]
Found the solution. We can used two different FLEXCOMM ports with signal sharing and using one for TX and the other one for RX.
