### ISSUE TITLE
Missing fsl_lpi2c_freertos driver files for PR.

### ISSUE THREAD

**Issue by Hadatko** [nxp-mcuxpresso/mcux-sdk#7]
**Is your enhancement proposal related to a problem? Please describe.**
Hi, i have issue with fsl_lpi2c_freertos driver. We are using it and it is using dynamicly allocated freertos semaphore/mutex. I made a small changes to support also staticly allocated space. But i cannot find header and source file here. How can i push PR for this files?

**Describe the solution you'd like**
*header file:*
![image](https://user-images.githubusercontent.com/13130700/110598712-595e0e80-8182-11eb-98c3-33977837be78.png)

*source file:*
![image](https://user-images.githubusercontent.com/13130700/110598653-48150200-8182-11eb-89a2-5dc61fbcc5e0.png)

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by nxp-susan** [comment]
Hi @Hadatko, appreciate for your contribution. However, peripheral drivers with middleware support are not included in this repository because currently the project does not include middleware. I have forward your suggestion to develop team for them to check, thanks.

**Comment by Hadatko** [comment]
Hi @nxp-susan  thank you very much for forwarding code to development team. I just found out bug in my propose. I replaced mutex type by mistake. Take that into account please. (Non recursive with recursive)

**Comment by Hadatko** [comment]
![image](https://user-images.githubusercontent.com/13130700/110758027-54fe2800-824c-11eb-8664-a8cd1f60f8e9.png)

**Comment by nxp-susan** [comment]
Hi @Hadatko, thanks for the update. I shared the link to develop team and they should be able to check your update.

**Comment by Hadatko** [comment]
Thank you for quick response. I am looking forward for your outputs.

**Comment by Hadatko** [comment]
Any update here?

**Comment by DavidJurajdaNXP** [comment]
Hi @Hadatko , feel free to raise pull request. FreeRTOS support is available on github now.
https://github.com/NXPmicro/mcux-sdk/tree/main/drivers/lpi2c

**Comment by Hadatko** [comment]
PR created.

**Comment by Hadatko** [comment]
Thank you for the info. Not happy, but understand.
